### ISSUE TITLE
Hoverzoom+ not working with i.redd.it Images/videos

### ISSUE THREAD

**Issue by Raijku** [extesy/hoverzoom#435] opened 2019-03-16 22:12 UTC
Hoverzoom+ currently not working with i.redd.it images/videos.
-----------------------------------
Reddit.com or old.reddit.com
---------------------------------------
Hoverzoom+ - Version 1.0.134
Chrome Version 73.0.3683.75

**Comment by michiel2304** [comment] 2019-03-17 14:56
For me sometimes it does show a video, but instead of skipping forwards while scrolling it just moves downwards.

**Comment by Raijku** [comment] 2019-03-17 14:58
That seems to happen on videos in general (YouTube)

**Comment by extesy** [comment] 2019-03-17 22:10
@Raijku It's working for me. Please follow an issue template otherwise I can't diagnose the problem.

**Comment by Raijku** [comment] 2019-03-17 23:36
Hi, sorry I didn't follow the template as this as happening with all i.redd.it/v.redd.it links I thought it was easily reproducible. Here you go with the template.

## Description of the problem
Hoverzoom+ is not "opening" i.redd.it images and v.redd.it videos (images and videos hosted on reddit)

## Url of the page where the problem occurs (not the image url)
https://www.reddit.com/   or  https://www.old.reddit.com/

## Steps to reproduce the problem (include image url here)
1. Open https://www.reddit.com/   or  https://www.old.reddit.com/

2. Hover any reddit hosted image/video  (e.g. https://www.reddit.com/r/sports/comments/b29240/mario_hezonja_blocks_lbj_to_take_the_w_for_the/)

## OS version, extension version (Chrome only, Firefox is not supported)
Hoverzoom+ - Version 1.0.134
Chrome Version 73.0.3683.75

**Comment by caseyo4** [comment] 2019-03-18 02:31
I have experienced this as well.

**Comment by Raijku** [comment] 2019-03-18 19:35
Can confirm it's the latest chrome update breaking it.
On previous version it's working perfectly.

**Comment by caseyo4** [comment] 2019-03-19 12:22
Yes, the latest Chrome version broke it.  Is this going to be addressed?

**Comment by extesy** [comment] 2019-03-19 14:17
@caseyo4 Yes, it is going to be addressed.

**Comment by extesy** [comment] 2019-03-19 15:40
Hey @mrdziuban, I would appreciate some help here. Chrome 73 is doing something weird here and xmlDoc ends up being empty inside a promise. Fallback DASH_600_K link doesn't work either.

**Comment by rootameen** [comment] 2019-03-23 15:34
What I noticed in gfycat and imgur gifs that it does indeed skip forward, but it also scrolls the page and loses focus.

If you try it while on top of the page and scroll-up, it works fine, as the page itself doesn't scroll.

**Comment by mrdziuban** [comment] 2019-03-23 20:51
#437 fixes the problem of `xmlDoc` being empty, which fixes `v.redd.it` URLs. I can't reproduce any issues with `i.redd.it` URLs though.

**Comment by rmp135** [comment] 2019-03-24 08:38
The scrolling behaviour in Chrome 73 has changed. I'd imagine this is what causes the bug. https://developers.google.com/web/updates/2019/02/scrolling-intervention

**Comment by extesy** [comment] 2019-03-26 02:21
Fixed in 1.0.135

**Closed by extesy** 2019-03-26 02:21 UTC
Labels: update existing plugin

**Comment by caseyo4** [comment] 2019-03-26 12:48
Works great.  Thanks again!
