### ISSUE TITLE
When will they add a backup of the settings? Backup and Export

### ISSUE THREAD

**Issue by userskill** [extesy/hoverzoom#990] opened 2022-08-03 13:11 UTC
Hello. There are not enough Backup settings and Export of all settings

**Comment by extesy** [comment] 2022-08-03 16:09
Duplicate of #687.

**Closed by extesy** 2022-08-03 16:09 UTC

**Comment by userskill** [comment] 2022-08-03 17:01
> ###

I wrote because I didn't add a useful function. There the answer is no
