### ISSUE TITLE
Add support for :   x.com

### ISSUE THREAD

**Issue by GeorgeSpelvin** [extesy/hoverzoom#1353] opened 2024-05-18 17:40 UTC
**What is the URL of the website**
https://www.X.com/

**Why we should add support for the website?**
Elon has retired twitter.com, all links are now x.com
This completely breaks the extension on Twitter/X

**Comment by extesy** [comment] 2024-05-19 15:48
Duplicate of #1351

**Closed by extesy** 2024-05-19 15:48 UTC
Labels: enhancement
