### ISSUE TITLE
If logged with account google, the app not work on google image...

### ISSUE THREAD

**Issue by M1rr0r-GitHub** [extesy/hoverzoom#473] opened 2019-11-08 15:10 UTC
If logged with account google, the app not work on google image, if not logged on google, the app work.

 - OS: Windows 10
 - Browser Chrome
 - Version 78.0.3904.97 (Build ufficiale) (a 64 bit)

**Comment by extesy** [comment] 2020-02-05 21:27
Duplicate of #463

**Closed by extesy** 2020-02-05 21:27 UTC
