### ISSUE TITLE
Add support for : redgifs.com

### ISSUE THREAD

**Issue by Razorleader1** [extesy/hoverzoom#518] opened 2020-05-28 18:42 UTC
**What is the URL of the website**
redgifs.com

**Why we should add support for the website?**
Describe why you need hoverzoom for that website

It's an offshoot of Gfycat. It gets a lot of use on reddit. Hoverzoom currenty doesn't work on the redgifs.com links.

**Comment by extesy** [comment] 2020-05-28 20:42
Duplicate of #508 and #517.

**Closed by extesy** 2020-05-28 20:42 UTC
Labels: enhancement
