### ISSUE TITLE
Image Saving Stopped working after 1.0.206

### ISSUE THREAD

**Issue by jellyachilles** [extesy/hoverzoom#1152] opened 2023-05-29 08:45 UTC
As of [1.0.206](https://github.com/extesy/hoverzoom/tree/1.0.206), action key to save no longer works and the option to enable "Allow downloading images using action key" no longer exist. In fact the only action key that works is open in new window/tab.

**To Reproduce**
1. Hover over an image
2. Image pops up
3. Use assigned action key to save or zoom
4. Doesn't save or zoom
5. Go to Advanced Settings
6. 'Allow downloading images using action key' option is gone

**Screenshots**

![firefox_XqtwoWcfRf](https://github.com/extesy/hoverzoom/assets/134922258/880d76ac-ef59-43a3-b928-c01faecd75fc)

**Comment by extesy** [comment] 2023-05-29 15:28
@jellyachilles Just checked and it works for me on reddit. Please provide specific links.

**Comment by jellyachilles** [comment] 2023-05-29 23:37
Desktop
Win 10, version 22H2
Firefox Version 113.0.2 64 bit
Hoverzoom+ 1.0.206

Additional Context
I have a separate firefox profile with 1.0.205 version of hoverzoom+ and it works perfectly. The update to 1.0.206 somehow broke action key saving functionality, hours before the automatic update it was working fine.

**Comment by extesy** [comment] 2024-05-30 22:20
Duplicate of #978

**Closed by extesy** 2024-05-30 22:20 UTC
Labels: firefox
