### ISSUE TITLE
Delay not working 

### ISSUE THREAD

**Issue by designbypepper** [extesy/hoverzoom#161] opened 2016-10-31 23:32 UTC
Delay setting not working, Images appear immediately, driving me nuts.  Tried changing to 3 seconds, but still not delayed.

**Comment by extesy** [comment] 2016-10-31 23:48
Duplicate of #142

**Closed by extesy** 2016-10-31 23:48 UTC

**Comment by designbypepper** [comment] 2016-10-31 23:50
#142 is closed

**Comment by extesy** [comment] 2016-11-01 01:46
@designbypepper #142 is not closed, it's still open.
