### ISSUE TITLE
Facebook images not working but linked images do

### ISSUE THREAD

**Issue by ivanoleo** [extesy/hoverzoom#229] opened 2017-02-07 22:05 UTC
Images that are uploaded to FB do not zoom. There is a flash of a rotating cursor, then nothing. But images that are within links (such as news articles with a photo) work just fine.

**Comment by extesy** [comment] 2017-02-07 22:41
Duplicate of #141.

**Closed by extesy** 2017-02-07 22:41 UTC
Labels: update existing plugin

**Comment by ivanoleo** [comment] 2017-02-07 22:44
So this is now closed, but is there a fix for it?

**Comment by extesy** [comment] 2017-02-07 23:26
No, you should follow existing ticket #141 instead.
