### ISSUE TITLE
 v3.redgifs.com and  redgifs.com Not loading in Reddit

### ISSUE THREAD

**Issue by Pentagrama200** [extesy/hoverzoom#1201] opened 2023-08-10 13:58 UTC
**Describe the bug**
 v3.redgifs.com and  redgifs.com Not loading in Reddit

**To Reproduce**
1. Go to 'www.reddit.com'
2. Click on 'any post with a [redgifs.com, or v3.redgifs.com]
3. See error, nothing happens. Nothing loads like the other type

**Expected behavior**
I expect it to pop up in a window like it does for the type on the page.
Like example ([i.redd.it]

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Mac iOS 13.4.1 (c) (22F770820d) ]
 - Browser [Opera)
 - Version [Opera One(version: 101.0.4843.43) (x86_64)

**Additional context**

**Comment by extesy** [comment] 2023-08-10 15:28
Thank you for the report, although it's a duplicate of #1194.

**Closed by extesy** 2023-08-10 15:28 UTC
