### ISSUE TITLE
gfycat hover zoom not working on Reddit

### ISSUE THREAD

**Issue by marcodj01** [extesy/hoverzoom#280] opened 2017-07-31 18:06 UTC
since today gfycat links are not played when hovering on them

**Comment by extesy** [comment] 2017-07-31 18:17
@Mte90 could this be caused by some of your changes?

**Comment by RumplesWrinkles** [comment] 2017-07-31 18:36
Also experiencing this issue. Imgur **_Gifv_** links also are not working. The first frame pops up, but the gif doesn't play. [Here's one example.](http://i.imgur.com/9iNqPvg.gifv)

Regular gif links seem to work. [Example hosted on reddit.](https://i.redd.it/cuu75dvkzycz.gif)

I'm also unable to scroll through Imgur albums now. [Example.](http://imgur.com/a/Dmlel)

YouTube videos also do not play on hover anymore. [Example.](https://www.youtube.com/watch?v=C_RApScdK5o)

**Comment by jwb118** [comment] 2017-07-31 18:42
Links are no longer being "marked as read" (added to history) 

Gifs in any format are not playing for me (gifv, gfycat, imgur, etc.)

Streamable videos no long play

All settings are set for the above to happen.

**Comment by Mte90** [comment] 2017-07-31 18:46
Uhm I am not sure we need to have the log in the console.

**Comment by extesy** [comment] 2017-07-31 18:47
@Mte90 Can you check @RumplesWrinkles's example above? I am able to reproduce the problem.

**Comment by extesy** [comment] 2017-07-31 18:48
I suspect it might be a side-effect of your jquery major version bump.

**Closed** 2017-08-01 02:14 UTC
Labels: update existing plugin

**Comment by Mte90** [comment] 2017-08-01 09:27
dammit, sorry yesterday I didn't had time to work on that and today yes but I saw that you already fixed!
