### ISSUE TITLE
Despite the update, it still doesn't work on ebay.de!

### ISSUE THREAD

**Issue by Werner-St** [extesy/hoverzoom#1113] opened 2023-03-28 09:06 UTC
Despite the update, it still doesn't work on ebay.de !

[## Url of the page where the problem occurs (not the image url)](https://www.ebay.de/sch/i.html?_from=R40&_trksid=p2334524.m570.l1313&_nkw=tischmultimeter&_sacat=0&LH_TitleDesc=0&rt=nc&_odkw=tischmultimeter&_osacat=0&LH_PrefLoc=3)

Please Fix it........
All Os Version , all Browser  Version

**Comment by extesy** [comment] 2023-03-28 22:20
Duplicate of the existing issue.

**Closed by extesy** 2023-03-28 22:20 UTC

**Comment by Werner-St** [comment] 2023-03-29 09:46
It was already faulty in version 1.0.202 and is not yet correct in the new version 1.0.203!
