### ISSUE TITLE
Previewed links are not getting added to browser history

### ISSUE THREAD

**Issue by jwb118** [extesy/hoverzoom#282] opened 2017-08-01 12:17 UTC
Viewed pictures and videos not being added to the browser history; specifically on Reddit

www.reddit.com

**Comment by extesy** [comment] 2017-08-01 18:26
@jwb118 The bug template was created for a reason, not to be deleted and replace with your own free-form report.

**Comment by jwb118** [comment] 2017-08-01 19:45
My apologies, I'm new to reporting....

my issue remains the same.

**Comment by gibbypip** [comment] 2017-08-01 21:42
This might help:

## Description of the problem
When trying to view images not contained within the reddit domain (*.reddit.com), the links are not added to the history in Chrome/links do not turn purple. Images hosted on Reddit's image platform seem to work at the time of this writing. 

Any combination of disable/enable of the setting "Add viewed pictures to the browser's history" in the extension, reloading the page, or exiting/opening the browser does not resolve the issue.

## Url of the page where the problem occurs (not the image url)
https://reddit.com/r/all

## Steps to reproduce the problem (include image url here)
1. Navigate to reddit
2. hover over non-reddit hosted image or gif i.e.: imgur.com
3. ???
4. profit?

## OS version, extension version
Win7 (fully patched), 
Chrome Version 59.0.3071.115 (Official Build) (64-bit) and 
Version 60.0.3112.78 (Official Build) (64-bit)

**Comment by ragnarkarlsson** [comment] 2017-08-01 22:49
Can confirm same symptoms as @gibbypip with 

Win10 (fully patched)
Chrome Version 60.0.3112.78 (Official Build) (64-bit)

**Comment by extesy** [comment] 2017-08-01 22:55
I am aware of the problem, there is no need to post additional confirmation. It is caused by @Mte90's jquery update. I will fix it later.

**Comment by extesy** [comment] 2017-08-02 02:45
Fixed in `1.0.121`

**Closed by extesy** 2017-08-02 02:45 UTC
Labels: bug
