### ISSUE TITLE
Save Image Action Key Not Working

### ISSUE THREAD

**Issue by Cr8zyIvan** [extesy/hoverzoom#1214] opened 2023-08-15 12:58 UTC
**Describe the bug**
The Save Image Action Key doesn't work.

I've changed the Keyboard Key to another Key to make sure the key I was using was not the problem. I switched with "T" (Open Image in New Tab). Using "T" with "Open Image in New Tab" works, "T" with "Save image" does not.

I changed the Download Folder. I tried specifying "No specific Folder" (to be Downloaded in the Downloads Folder directly), I tried using a Non-Existing Folder (perhaps HoverZoom needed to Created a Folder to work), I tried an Existing Empty Folder, and I tried an Existing Folder with Content. None of this worked.

Finally, I checked the Option "Enable Action Keys focus overlay message", and this did not solve the problem either. 

I've Downloaded images with Firefox's native Context Menu, and I've downloaded images with other Firefox Add-Ons which use Action Keys as well (using "A" with the "Cute Save Button" Add-On) which also worked.

I double checked the Permissions in Firefox's Extension Manager. "Download files and read and modify the browser’s download history" was checked (On).

I tried disabling other Add-Ons which can also Download Content. Hover Zoom+ still didn't work.

And finally, I've Reset Hover Zoom+ Options to see if there's an Option I checked that might have interfered, and still "Save Image" hasn't worked.

I don't know what else to check at this point.

Cheers

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by DohnJoe2** [comment] 2023-09-08 17:13
I have the same issue on Firefox, hasn't been working for more than month

**Comment by cheetcoad** [comment] 2023-09-10 15:25
same issue here so i just hit W to open image in a window and save it from there using right-click/save image as....

**Comment by k4rli** [comment] 2023-12-06 17:08
Same issue still exists.

**Comment by Sevenuno** [comment] 2023-12-19 02:27
Come here to confirm that it's still not working in FF.

**Comment by extesy** [comment] 2024-05-30 22:20
Duplicate of #978

**Closed by extesy** 2024-05-30 22:20 UTC
Labels: bug, firefox
