### ISSUE TITLE
problem downloading images

### ISSUE THREAD

**Issue by EnverAvci** [extesy/hoverzoom#1132] opened 2023-04-17 15:48 UTC
Hello When I download a photo with Hover Zoom, 3 identical photos download at the same time.
Google chrome
Windows 11
![ss](https://user-images.githubusercontent.com/96924550/232540677-ede31425-de84-4dff-8910-16a5edc92ea3.png)
![Ekran görüntüsü 2023-04-17 184801](https://user-images.githubusercontent.com/96924550/232540684-8f62f28b-a319-4502-98c8-c548e370feaf.png)

**Comment by albino1** [comment] 2023-04-17 16:10
https://github.com/extesy/hoverzoom/issues/1127

**Comment by extesy** [comment] 2023-04-17 19:33
Closing as duplicate of #1127.

**Closed by extesy** 2023-04-17 19:33 UTC
