### ISSUE TITLE
Hover Zoom+ Extension Unavailable on Chrome Store – Issue Fix Needed

### ISSUE THREAD

**Issue by ahmadsaadkhan** [extesy/hoverzoom#1514] opened 2024-12-26 09:34 UTC
The popular "Hover Zoom+" extension is no longer available on the Chrome Web Store due to non-compliance with best practices for Chrome extensions. This has caused functionality disruptions for users. Addressing the issue requires adherence to Chrome's updated extension policies. A resolution is needed to restore the extension's availability and functionality while ensuring compliance with Google's guidelines.

My Chrome Version 
Chrome
Version 131.0.6778.205 (Official Build) (64-bit)

**Comment by a2nath** [comment] 2024-12-27 00:48
It doesn't work at all nowadays, and hasn't worked in 2-3 weeks now. And I can confirm the message from the chrome store.

**Comment by extesy** [comment] 2024-12-27 02:38
Duplicate of #1395. There's an advice there on how to extend availability of V2 extensions.

**Closed by extesy** 2024-12-27 02:38 UTC
