### ISSUE TITLE
Pixiv doesn't work anymore with new URL's

### ISSUE THREAD

**Issue by molecast** [extesy/hoverzoom#461] opened 2019-09-24 13:45 UTC
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
Pixiv doesn't work anymore with new URL's

## Steps to reproduce the problem (include image url here)
1.
2.
3.

## OS version, extension version (Chrome only, Firefox is not supported)
Hover Zoom + v.1.0.137
Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)
Windows 10 v.1903 b.18362.356

**Comment by extesy** [comment] 2019-09-25 13:58
Duplicate of #462

**Closed by extesy** 2019-09-25 13:58 UTC
Labels: update existing plugin
