### ISSUE TITLE
Hover Zoom+ for Firefox - "Save image" Action Key does not work (Version 1.0.218)

### ISSUE THREAD

**Issue by isick1e** [extesy/hoverzoom#1387] opened 2024-08-07 00:25 UTC
**Describe the bug**
On Version 1.0.218 extension for Firefox, the "Save image" Action Key does not work to save an image that is currently hovered. This functionality works fine on the Chrome extension, however. 

All of the other Action Keys seem to work, aside from "Save image". I have just moved over to Firefox from Chrome, so I don't know how long this function hasn't worked. 

I tried to reinstall the extension fresh with all settings reset using the "Reset" and "Save" buttons to no avail. As seen in the screenshots below, under the extension permissions, only "Access your data for all websites" is enabled by default. 

I went ahead and enabled the three other Optional permissions "Download files and read and modify the browser’s download history", "Access browsing history", and "Access browser tabs". The "Save image" Action Key still doesn't download images. I have also enabled the "Enable Action Keys focus overlay message" setting to ensure the image is focused before trying to save it.

**To Reproduce**
1. Go to Google.com
2. Search "cats"
3. Click on Images
4. Hover over various image results and allow them to enlarge.
5. Press the "Save image" Action Key (default S)
6. Nothing happens, the image does not download.

_In the Screenshots section below, I will show the Console outputs when using the "Save image" Action Key._

**Expected behavior**
Pressing the desired Action Key on a hovered image should download the image to the set download location.

**Screenshots**
**_Screenshots of the default Hoverzoom+ Extension settings on Firefox:_**
![firefox_7r0Nfryllx](https://github.com/user-attachments/assets/69c8ff93-8a12-4a8e-a3f1-2f8fb9043520)

![firefox_ZjzspzdlWh](https://github.com/user-attachments/assets/76d1ef2e-6ffd-41c8-9001-cfe177056b66)

**_Screenshots of my modified Hoverzoom+ Extension settings on Firefox to enable optional features:_**

![firefox_Fuv10tL4rG](https://github.com/user-attachments/assets/c2d36e2f-5bfc-4537-a3ff-75f7d87f405f)

_**Screenshot of the Firefox Console (F12) and the Hover Zoom+ Extension debug console outputs when hovering over the first 3 Google image results and pressing the "Save image" Action Key.**_

![firefox_nBHuxJhcBC](https://github.com/user-attachments/assets/6a67c92d-c920-44e0-ad3f-2c227a2ba10c)

When I press the "Save image" Action Key, the Firefox Console outputs "Download: (file URL)" and the extension debug console outputs "downloadFile: [object object]" then "downloadFile granted: undefined", without downloading anything at all. 

However, when I try the "Save image" Action Key on the Chrome extension, the file does download as expected, and the following Console output is generated:

![chrome_SUMzQbAdax](https://github.com/user-attachments/assets/83103864-d05b-4e1c-a921-eee20cc83f95)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 10.0.19045 Build 19045
 - Browser: Firefox
 - Version: 129.0 (64-bit)

**Comment by Himbosuarus** [comment] 2024-08-19 23:33
Having the same issue I believe

**Comment by LiliaDoe** [comment] 2024-10-26 04:27
The issue is in the onMessage function in background.js. For some reason chrome.permissions.request is not returning a promise in Firefox 131.0.3

**Comment by extesy** [comment] 2024-10-27 15:33
@LiliaDoe Yep, I tracked it down to the same place, but I have no idea why Firefox would behave that way. Seems like a bug in Firefox?

**Comment by LiliaDoe** [comment] 2024-10-27 15:50
@extesy I'd say it is as well. There is a workaround I discovered, to first check for the permission with permissions.contains, but it's not ideal

**Comment by extesy** [comment] 2024-10-28 00:40
Fixed in 02bb4426d6ed607852111cd7cb691e5ec06489bc. Will be available in the next release.

**Closed by extesy** 2024-10-28 00:40 UTC
Labels: bug, firefox
