### ISSUE TITLE
This happens for any image: I press the shortcut key to save the image, but instead opens the image in the same window and doesn't open the file explorer to save it like it normally did

### ISSUE THREAD

**Issue by spyderdevyn** [extesy/hoverzoom#353] opened 2018-03-16 02:12 UTC
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
Pressed shortcut key
Instead of the extension opening file explorer to save the image, it loads the image in the same tab and doesn't let you save it at all

## Url of the page where the problem occurs (not the image url)
(google.ca, etc...)

## Steps to reproduce the problem (include image url here)
1. Pressed shortcut key
2. Opens the image on the same tab
3. Doesn't allow you to save basically, just opens the image in the current tab you viewed it in

## OS version, extension version (Chrome only, Firefox is not supported)
Chrome

**Comment by extesy** [comment] 2018-03-18 16:25
Duplicate of #344

**Closed by extesy** 2018-03-18 16:25 UTC
