### ISSUE TITLE
Broken in Reddit Galleries

### ISSUE THREAD

**Issue by esotericsean** [extesy/hoverzoom#544] opened 2020-08-03 21:54 UTC
HoverZoom does not work when viewing reddit galleries.

reddit.com

1. Go to reddit.com
2. Hover on a reddit gallery URL, such as: https://www.reddit.com/gallery/i2y6rb
3. Does not work

macOS 10.14.6 | Brave 1.11.104 | HoverZoom+ 1.0.150

**Comment by extesy** [comment] 2020-08-04 06:09
Duplicate of #537. Wait for version 1.0.151 to be published.

**Closed by extesy** 2020-08-04 06:09 UTC
