### ISSUE TITLE
.blink class too generic and interferes quickly

### ISSUE THREAD

**Issue by jkctech** [extesy/hoverzoom#860] opened 2022-01-06 16:07 UTC
## Description of the problem
The CSS class name "blink" is too generic and quickly causes issues with existing CSS on sites.

## Url of the page where the problem occurs
[https://www.112centraal.nl/melding?id=3358047](https://www.112centraal.nl/melding?id=3358047)

## Steps to reproduce the problem
1. Site shows blinking element with "blink" as class name
2. Hoverzoom's CSS overrides since it's inserted in the DOM
3. See image: 
![b9682a48140110f34021bd03b2ad0336](https://user-images.githubusercontent.com/2072890/148412536-9a222065-296e-446c-862e-111f2bbf2047.png)

## Versions
Chrome Version 96.0.4664.110
Hoverzoom Version 1.0.186

## Possible solution
Either lower the inserted CSS priority or change the class name to something less generic.

**Comment by jkctech** [comment] 2022-01-06 16:13
Looks like issue has been addressed in following commits by also changing classname to blinkWarning instead.
Might still be a little generic imho.

Commits f3e48ab7ca65d2d03aae349a33d6d297ff9af155 and a411623d37fce2e6859bfa069ab20fd43ded34fd

**Comment by extesy** [comment] 2022-01-07 05:07
Duplicate of #847, fixed in version `1.0.187`.

**Closed by extesy** 2022-01-07 05:07 UTC
