### ISSUE TITLE
facebook not working

### ISSUE THREAD

**Issue by vanja-krk** [extesy/hoverzoom#119] opened 2016-08-11 12:22 UTC
as i can see this mark "update existing plugin", but i do not see any difference. i updated it via developer tools, i uninstalled-reinstalled, still no go. 

version is  1.0.88.

please advice.

thanks in advance!

**Comment by extesy** [comment] 2016-08-11 15:06
Duplicate of #118

**Closed by extesy** 2016-08-11 15:06 UTC
