### ISSUE TITLE
Hoverzoom won't work on .gifv files

### ISSUE THREAD

**Issue by DaenerysTargaryen69** [extesy/hoverzoom#51] opened 2016-03-11 12:21 UTC
Hoverzoom won't work on .gifv files

**Comment by extesy** [comment] 2016-03-11 15:39
@DaenerysTargaryen69 It does work for me. What is the page url where you don't see it working?

**Comment by extesy** [comment] 2016-03-16 17:21
Closing as "can't reproduce".

**Closed by extesy** 2016-03-16 17:21 UTC
Labels: bug
