### ISSUE TITLE
CHROME WEB STORE  - Hover Zoom + ...This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions.

### ISSUE THREAD

**Issue by pccaptain4911** [extesy/hoverzoom#1426] opened 2024-10-13 21:31 UTC
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Steps to reproduce the problem (include image url here)
1.
2.
3.

**Comment by extesy** [comment] 2024-10-14 03:30
Duplicate of #1395

**Closed by extesy** 2024-10-14 03:30 UTC
