### ISSUE TITLE
Firefox release

### ISSUE THREAD

**Issue by Mte90** [extesy/hoverzoom#273] opened 2017-07-29 14:15 UTC
Actually with WebExtension API (https://developer.mozilla.org/it/Add-ons/WebExtensions) is possible to use Chrome extension in Firefox without issue or porting.

I loaded the extension on Firefox and is working without issues.

**Comment by Mte90** [comment] 2017-07-30 19:06
I am trying to get working on firefox with #274

**Comment by extesy** [comment] 2017-07-31 00:24
I've just pushed the latest updates to Chrome Webstore, should be available soon for everybody. Do you have any good suggestions about what should I do with Firefox support? I don't personally use it so I'm not sure how to better go about it. Should I publish it as a new extension on Firefox's webstore or it can import Chrome extensions somehow?

**Comment by Mo2000** [comment] 2017-07-31 01:02
Can you please post here when this is posted on the Firefox addons website?

**Comment by extesy** [comment] 2017-07-31 01:49
I haven't posted it yet as I'm waiting for @Mte90's suggestion since he seems to be very familiar with Firefox extension model.

**Comment by Mte90** [comment] 2017-07-31 10:19
It is pretty simple :-)
You have to do a zip like for chrome and upload on addons.mozilla.org.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Publishing_your_WebExtension

The only difference that the publish on firefox require days for the review that is manual (especially on a new extension) but I can speed up the process asking on IRC.
If the review process find something that is not good for Firefox you will receive an email with a list of change that you need to do but I an help on that :-)

**Comment by mathew832** [comment] 2017-08-02 03:12
I'm here also because I'm  using it on Firefox. I used an extension called Chrome Store Foxified which converted it to XPI and signed it using my own personal Mozilla account so I could keep it installed. It works great and I doubt you'd have any trouble porting it officially. The few other hoverzoom-type extensions on FF don't have e10s support and apparently don't plan to. This would be a good opportunity to step in and be the best and only one that works with it. Ironic that I have to use a Chrome addon to work well with the newest Firefox.

**Comment by extesy** [comment] 2017-08-02 04:04
Ok, I have submitted it as https://addons.mozilla.org/en-US/firefox/addon/hover-zoom-plus/ - we'll see how the review goes.

**Comment by mathew832** [comment] 2017-08-02 05:27
Awesome. Though clicking the install button once gives:

"This add-on has not been reviewed by Mozilla and can't be installed on release versions of Firefox 43 and above. Be careful when installing third-party software that might harm your computer." 

Downloading the XPI and unzipping, I noticed you don't have an install.rdf file. I'm sure that's also what it mentions v43 and below. The install file suggest which versions of FF it's compatible with and a few other things. I don't know a whole lot about FF extension file structure but apparently it's needed (source: http://kb.mozillazine.org/Install.rdf). I created one, zipped it and manually installed and FF gave an error about it being not signed. I suspect it's all that's needed.

According to what I've read, FF's webextension API is aiming to be %100 compatible with Chrome's  extensions so hopefully you don't run into any other issues. As I said, it's working ok as I installed it.

**Comment by Mte90** [comment] 2017-08-02 08:59
The alert actually is because the addons not received yet a review, when will receive that will disappear that alert.
For the install.rdf the new webext doesn't require this file anymore, it is the store that automatically insert this files but @caitmuenster can help to understand why is not installable with this error with the corrupt warning (I get the same error).
Maybe there is a bug in addons.mozilla.org

**Comment by Mte90** [comment] 2017-08-03 11:09
I asked to the reviewers about the status and the problem is that the extension as over 270 js files so will require time because in AMO at every release they check the code (only when there are differences of course) and because is the first release they have to check everything.

**Comment by Mo2000** [comment] 2017-08-04 00:17
This is one of the things I like about Mozilla over Google. They check the code of all of the addons for Firefox. I think Google just uses some automated system.

**Comment by CheungTatMing** [comment] 2017-08-18 12:39
It is not able install from https://addons.mozilla.org/en-US/firefox/addon/hover-zoom-plus/
It said the package is broken or corrupt.

**Comment by stil** [comment] 2017-08-23 16:04
@extesy What happened to addon link? It says "not found", did you remove it or it was reviewers who denied the publication?

**Comment by extesy** [comment] 2017-08-24 05:16
It didn't pass the review

**Comment by Mte90** [comment] 2017-08-24 09:31
What are the issue reported?

**Comment by stil** [comment] 2017-08-29 18:29
We need to know what issues were found during review process so maybe we can help fix them.
It's an open source project, you shouldn't keep this information in secret from other contributors.

**Comment by extesy** [comment] 2017-08-29 20:25
> Your add-on, Hover Zoom+ 1.0.121, has been reviewed and did not meet the criteria for being hosted in our gallery.
> 
> Reviewer:
> Bogdan Matei
> 
> Comments:
> This version didn&#39;t pass review because of the following problems:
> 
> 1) Please include all  assets such as images, fonts, or css files locally inside the add-on instead of using them remotely. Here are some examples:
> - gumby.css
> - zinio.js
> 
> 2) Please add a privacy policy to this add-on that details which remote API calls are being made and to what services. If your add-on makes it apparent to websites that it is installed, this must also be mentioned. The policy should be about the extension only, not a copy of the website&#39;s privacy policy. It should also be the actual text, as opposed to a link to a privacy policy on a website.

@stil I'm not keeping it secret. If I haven't been replying immediately that means I had reasons for doing so.

**Comment by stil** [comment] 2017-08-29 23:39
I created pull request that embeds remote fonts from `gumby.css`. I believe there are no remote assets in `zinio.js`, it must be a mistake.

Privacy policy fix should be simple. MDN docs say that

> If your app doesn't collect, use, store, and share or disclose any information about people, simply enter "This application doesn't collect, use, store, and share or disclose any information about the user or any other person." in the Marketplace Privacy Policy field.

https://developer.mozilla.org/en-US/Marketplace/Publishing/Policies_and_Guidelines/Privacy_policies

Does it apply to HoverZoom+ extension? If so, it can be phrased like that:
> HoverZoom+ browser extension doesn't collect, use, store, and share or disclose any information about the user or any other person.

**Comment by BubiBalboa** [comment] 2017-09-22 09:30
@extesy Mozilla just went live with an automated review system for webextensions. If you'd merge @stil's contribution and resubmitted the addon it would the published right away. No waiting required.

**Comment by stil** [comment] 2017-09-22 18:17
Until there is official release, you can use my own submission:
https://addons.mozilla.org/en/firefox/addon/hoverzoom-plus

It passed the review in couple of minutes. I'm going to remove it when @extesy decides to release official package. I marked it "experimental" to underline the fact it isn't official.

I'm not sure why, but you need to go to Addon options and check "Enable Hover Zoom+" then click Save. I think it should be enabled by default right after installation.

**Comment by BubiBalboa** [comment] 2017-09-22 18:55
Nice! There are some bugs but it's a very nice teaser of what to (hopefully) expect from the full release.

**Comment by italiani** [comment] 2017-10-10 01:01
@stil I have a problem https
"[HoverZoom] Failed to load image: http://cs841233.userapi.com/v841233018/249e9/Rj-sPCbBHXw.jpg
Trying next one: https://cs841233.userapi.com/v841233018/249e9/Rj-sPCbBHXw.jpg
hoverzoom.js:658:21
[HoverZoom] Failed to load image: null"

**Comment by tractorpulledpork** [comment] 2018-01-06 01:04
I have a minor bugfix for firefox but the issue template specifically says Firefox is not supported so I'm posting it here:

The '[mousewheel](https://developer.mozilla.org/en-US/docs/Web/Events/mousewheel)' event does not work in Firefox Quantum. It is non-standard and can be replaced with the better supported '[wheel](https://developer.mozilla.org/en-US/docs/Web/Events/wheel#Browser_compatibility)' event. This is impacting album and video navigation.

Also, it seems that https://addons.mozilla.org/en/firefox/addon/hoverzoom-plus is now a dead link.

**Comment by stil** [comment] 2018-01-06 16:41
> Also, it seems that https://addons.mozilla.org/en/firefox/addon/hoverzoom-plus is now a dead link.

@tractorpulledpork It was removed by Mozilla for violation because it included minified libs (jQuery Mobile, Modernizr, Gumby). I have reuploaded it with uncompressed version of this libs and it's up again.

**Comment by 07416** [comment] 2018-02-20 15:29
@extesy Is Firefox currently supported? There appears to be a bug in the Firefox version (configuration settings reset when closing the browser) and I'd like to create an issue.
If Firefox is supported, please update the issue template.

**Comment by ScottRFrost** [comment] 2018-05-10 20:25
The root README.md should be updated with a link to @stil 's fork until @extesy can get the code merged in.  It was difficult for me to find this and the first non-heading line of the README.md seems to indicate that Google Chrome is the only supported browser.

**Comment by 07416** [comment] 2018-08-05 18:33
> While I'm here I should note that I can't reproduce @07416 's bug. When I close and re-open Firefox my settings are retained. Firefox Developer Edition 61.0b3 (64-bit).

This issue was potentially caused by clearing localStorage.

**Comment by 07416** [comment] 2018-08-05 18:40
@stil Is this [the repository](https://github.com/stil/hoverzoom) for your fork? Can you please update the description and at least make clear that the extension is for Firefox?

It also confuses me that you've posted the extension to [Firefox Add-ons](https://addons.mozilla.org/en-US/firefox/addon/hoverzoom-plus/) under a different name and I'm still not fully certain if you're the author.

**Comment by LoneFenris** [comment] 2018-12-15 21:16
@stil Are you still maintaining the Firefox addon? Does it still need to be maintained separately or is the code now ready for @extesy to roll releases for both browsers?

**Comment by 07416** [comment] 2019-03-27 22:08
@extesy Are there current plans to support Firefox?

**Comment by 07416** [comment] 2019-03-27 22:08
@stil Why you haven't branded your version as a fork? You have copied the description from the Chrome addons page:

https://chrome.google.com/webstore/detail/hover-zoom%20/pccckmaobkjjboncdfnnofkonhgpceea
https://addons.mozilla.org/en-US/firefox/addon/hoverzoom-plus/

Because of this [the repo receives issues for the Firefox version, all closed as invalid](https://github.com/extesy/hoverzoom/issues?utf8=%E2%9C%93&q=firefox+in%3Atitle). 

The name of the original creator is displayed in the addon menu:

> Version 1.0.132 -  2014-2018 Oleg Anashkin

The Firefox version is now out of date (1.0.132, last updated Jun 23, 2018).

**Comment by ScottRFrost** [comment] 2019-03-28 14:39
lol @07416 necro poster.  There have been no commit's to @stil 's repo in almost a year, I think you can consider this project dead.  Just use Imagus on Firefox - https://addons.mozilla.org/en-US/firefox/addon/imagus/

**Comment by LoneFenris** [comment] 2019-03-28 17:39
It looks like @extesy has merged all the changes @stil made to pass review by Mozilla. I'm not sure if there's anything else still stopping supporting Firefox from this project other than maybe @stil 's submission being in the way?

**Comment by extesy** [comment] 2019-03-29 02:39
I'm trying to remove @stil's addon from AMO, will see how it goes.

**Comment by 07416** [comment] 2019-04-15 10:21
> 
> 
> I'm trying to remove @stil's addon from AMO, will see how it goes.

The addon has been deleted: https://addons.mozilla.org/en-US/firefox/addon/hoverzoom-plus/

**Comment by K0FFing** [comment] 2019-08-05 12:21
> 
> 
> lol @07416 necro poster. There have been no commit's to @stil 's repo in almost a year, I think you can consider this project dead. Just use Imagus on Firefox - https://addons.mozilla.org/en-US/firefox/addon/imagus/

sadly and after years, the plugin is officially dead, I never got the support I needed for firefox and Imagus works perfectly. I was a big fan but they let this plugin die. It's time to leave it behind and migrate to something with better support and more functional, @07416 thanks for the suggestion, I'm already enjoying it on Twitter and Facebook without any problem

**Comment by extesy** [comment] 2022-08-05 20:09
Firefox is supported now.

**Closed by extesy** 2022-08-05 20:09 UTC

**Comment by ScottRFrost** [comment] 2022-08-06 03:57
Closing out 5-year-old issues positively feels good man!

Thank you for your hard work!

**Comment by extesy** [comment] 2022-08-06 16:59
Well, technically Firefox has been already supported for a while but I found this old open issue and thought it would be a good idea to close it. There are several clones on Firefox marketplace, make sure to use this one: https://addons.mozilla.org/en-US/firefox/addon/hover-zoom-plus/
