### ISSUE TITLE
Lost the "save to..." functionality on zoomed images on reddit

### ISSUE THREAD

**Issue by Frank-Belanger** [extesy/hoverzoom#995] opened 2022-08-07 22:38 UTC
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
I was able to hover over images and videos, press ctrl+s and save automatically to my downloads folder. Now, it tries to save the whole page as html.

## Url of the page where the problem occurs (not the image url)
Happens on reddit.com and all subdomains

## Steps to reproduce the problem (include image url here)
1. Go to www.reddit.com
2. Hover mouse over an image (for example: https://www.reddit.com/gallery/wig53j)
3. Press ctrl+s

**Expected behavior:** Automatically save image/video to chrome downloads folder

**Actual Behavior:** "Save As" Dialog box opens to direct user where to save page as html document.

## OS version, extension version
Windows 10 Education 21H2
Chrome 103.0.5060.134
Hover Zoom 1.0.195

**Comment by extesy** [comment] 2022-08-07 23:47
@Frank-Belanger Does the regular `S` key work? Please check the "action keys" configuration in the extension options.

**Comment by Frank-Belanger** [comment] 2022-08-08 12:48
It doesn't seem to work either. Weird. I also tried the `S` key on Firefox (version 103.0.1) and doesn't seem to work on either reddit nor google images.

**Comment by RumplesWrinkles** [comment] 2023-01-10 21:20
I'm experiencing this issue too. Unable to save hovered images with "S" on reddit.

**Comment by extesy** [comment] 2024-05-30 22:20
Duplicate of #978

**Closed by extesy** 2024-05-30 22:20 UTC
