### ISSUE TITLE
Action key ( S ) 

### ISSUE THREAD

**Issue by maynardx11** [extesy/hoverzoom#86] opened 2016-05-15 14:22 UTC
when i use action key S it save but it save multiple images, so when i press S it download 3 images. 

Hope that you can fix this bug

**Comment by extesy** [comment] 2016-05-15 16:00
@maynardx11 Please provide url of the page where you see this behavior and what image are you trying to save.

**Comment by extesy** [comment] 2016-05-15 16:02
Actually, this is a duplicate of #71. Please provide more details in that ticket.

**Closed by extesy** 2016-05-15 16:02 UTC
Labels: bug, can't reproduce
