### ISSUE TITLE
Facebook profile picture zoom bug

### ISSUE THREAD

**Issue by antivirtel** [extesy/hoverzoom#244] opened 2017-03-04 11:25 UTC
I've been using an extension previously which was zoomed the FB profile image also. Can you implement this feature? Now it works like this:
![screenshot](https://i.imgur.com/fPIKnB0.png)

**Comment by extesy** [comment] 2017-03-04 15:33
Duplicate of #141.

**Closed by extesy** 2017-03-04 15:33 UTC
