### ISSUE TITLE
Hoverzoom+ not loading thumbnail images & profile pictures on posts on FB timeline

### ISSUE THREAD

**Issue by kuspie** [extesy/hoverzoom#165] opened 2016-11-06 17:11 UTC
Added the extension today.  This is what occurs when hovering over the thumbs and profile pics.

![image](https://cloud.githubusercontent.com/assets/23294976/20039862/ede03204-a400-11e6-982f-816e0e7de1a0.jpg)

**Comment by extesy** [comment] 2016-11-06 17:21
Duplicate of #126

**Closed by extesy** 2016-11-06 17:21 UTC

**Comment by kuspie** [comment] 2016-11-06 17:26
Sorry, did I miss something?  I realize it's a dupe but has it been fixed?  I'm new to gitub, thx.

**Comment by extesy** [comment] 2016-11-06 20:43
No, it hasn't been fixed yet. There's no need to open two identical issues for the same problem.
