### ISSUE TITLE
Hot key for save feature is not working

### ISSUE THREAD

**Issue by star777star** [extesy/hoverzoom#1356] opened 2024-05-30 06:05 UTC
**Describe the bug**
After loading the web page (Images search page) on hover the mouse on any image, popup open with desired dimension. But save feature is not functioning while pressing 'S' key.

**To Reproduce**
1) hover a image
2) popup open with hiovered image
3) now press S key for save.
4) image is not saved

**Expected behavior**
On pressing 'S', the popup image should be saved.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WINDOWS 10
 - Browser [Mozilla Firefoxi]
 - Version [126.0.1]

**Additional context**

**Comment by extesy** [comment] 2024-05-30 22:19
Duplicate of #978

**Closed by extesy** 2024-05-30 22:19 UTC
