### ISSUE TITLE
imgur images won't load

### ISSUE THREAD

**Issue by dr-norton** [extesy/hoverzoom#259] opened 2017-04-19 20:25 UTC
## Description of the problem
imgur images won't load

## Url of the page where the problem occurs
http://i.imgur.com/6nPonTI.jpg

## Steps to reproduce the problem
1. move the cursor on the link above
2.
3.

## OS version, extension version
macos 10.12.4
1.0.116

**Comment by extesy** [comment] 2017-04-19 20:30
@dr-norton please provide url of the page **where the problem occurs**, not url of the image.

**Comment by dr-norton** [comment] 2017-04-19 20:47
in addition to this very page, take a look to:
https://eksisozluk.com/entry/34514291
or for more:
https://www.reddit.com/domain/i.imgur.com/search?q=jpg&restrict_sr=on

**Comment by dr-norton** [comment] 2017-04-20 05:40
strangely gifv links work but jpg or png links don't, like on that page:
https://www.reddit.com/domain/i.imgur.com/

the images directly from imgur also work:
https://teknoseyir.com/durum/176211

**Comment by Dumbaz** [comment] 2017-04-21 09:38
Are you sure there is not another extension in your browser that hinders hoverzoom from working? I will test the image above on my macbook as soon as I get home, but strongly suspect that it will be working.
For starters, you should list your
* Chrome Version
* Enabled Extensions

**Comment by dr-norton** [comment] 2017-04-21 14:05
thanks for the tip but it didn't work. i disabled all extensions, then tried it with these two versions of chrome (got an update at the same time, so...):
57.0.2987.133 (64-bit)
58.0.3029.81 (64-bit)

**Comment by extesy** [comment] 2017-04-21 16:56
Maybe you have added imgur to exclusions in the extension settings?

**Comment by dr-norton** [comment] 2017-04-21 20:51
nope. but anyway, i give up, apparently it's just my system. if i can find the cause i will post it here. thanks guys.

**Comment by Dumbaz** [comment] 2017-04-23 07:39
Cannot reproduce on my Macbook.

```
macOS Sierra Version 10.12.4 (16E195)
Chrome Version 57.0.2987.133 (64-bit)
```

**Comment by dr-norton** [comment] 2017-04-23 11:05
i found the problem at last, solved the issue, and it's not about hoverzoom. sorry, i took your time but i couldn't solve it without your comments obviously. i was thinking there was a problem between hoverzoom & imgur. thanks everyone again.

here's the thing: i live in turkey and imgur is banned by government. but, the blocked domain is i.imgur.com, not imgur.com. so i added an ip address to my hosts file, i totally forgot till now, to get around. it's interesting that it works well with imagus but doesn't work with hoverzoom. another interesting point was animated images worked well but jpg/png files didn't work with hoverzoom; so i couldn't imagine there was a deeper problem in my system.

anyway, i found another ip address for i.imgur.com and changed my hosts line with it (151.101.36.193 i.imgur.com), now everything works great.

**Comment by extesy** [comment] 2017-04-23 17:16
Thanks for the follow up, @dr-norton and I'm glad you've been able to solve the problem. I'm closing the issue.

**Closed by extesy** 2017-04-23 17:16 UTC
Labels: can't reproduce
