### ISSUE TITLE
Losing settings on Chrome cache removal?

### ISSUE THREAD

**Issue by miklosUX** [extesy/hoverzoom#804] opened 2021-10-04 09:01 UTC
It seems I lose the custom settings, like whitelisted sites, keys to control functionalities... every time I delete the browser cache (nothing else, i.e. cookies) in Chrome, macOS (latest both).

A giant PITA to have to go back in and set everything back up. (Someone suggested the ability to export/import settings btw which I agree with, it would really help!)

**Desktop (please complete the following information):**
 - macOS 11.6 Big Sur
 - Chrome
 - Version 94.0.4606.71 (Official Build) (x86_64)

**Comment by extesy** [comment] 2021-10-04 20:58
This seems to be a duplicate of #687. The settings are currently stored in localStorage which apparently gets cleaned when the cache is removed.

**Comment by extesy** [comment] 2024-11-08 21:50
https://github.com/extesy/hoverzoom/commit/6988beeb48ffde1d1f81a3efb1ef52eca5007cfd adds import/export functionality, will be available in the next release.

**Closed by extesy** 2024-11-08 21:50 UTC
Labels: enhancement
