### ISSUE TITLE
Will there be support for new Reddit site?

### ISSUE THREAD

**Issue by jr611** [extesy/hoverzoom#388] opened 2018-06-21 23:41 UTC
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
support for new reddit

## Url of the page where the problem occurs (not the image url)
www.reddit.com

## Steps to reproduce the problem (include image url here)
1.
2.
3.

## OS version, extension version (Chrome only, Firefox is not supported)
chrome

**Comment by extesy** [comment] 2018-06-22 13:51
Duplicate of #373

**Closed by extesy** 2018-06-22 13:51 UTC
