### ISSUE TITLE
Feature request: New Tab Opening Direction Option

### ISSUE THREAD

**Issue by burakyak** [extesy/hoverzoom#386] opened 2018-06-20 12:24 UTC
Hi,
It's a great extension, loving it.
Whet I press "t", it opens the new tab on the left side in the tabs section.
It would be great to be able to turn on/off this behavior.

**Comment by ivan2340** [comment] 2018-06-20 22:06
@extesy this is a bug, duplicate of #336

**Comment by extesy** [comment] 2018-06-21 00:51
Ok, closing as duplicate of #336.

**Closed by extesy** 2018-06-21 00:51 UTC
Labels: duplicate
