### ISSUE TITLE
redgifs link on reddit doesnt work at all

### ISSUE THREAD

**Issue by zekecounter** [extesy/hoverzoom#996] opened 2022-08-10 01:38 UTC
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
Hover Zoom + is not currently able to work on redgifs.com links found on reddit in chrome, only thing the seems to work is when the thumbnail. Fair warning the following links will be NSFW heavy.

## Url of the page where the problem occurs (not the image url)

https://www.reddit.com/domain/redgifs.com/

## Steps to reproduce the problem (include image url here)
1. use the link provided above and hover on any of the  posts there.
2.  https://www.reddit.com/user/Naomi_Soraya/comments/wkebzh/_/    on this page, hover over the peach emoji  with the cursor 
3. https://www.reddit.com/user/audreylovessadie/comments/wk5n38/can_i_do_this_on_your_face/  on this page, hover over the post's title header. 

## OS version, extension version
windows 10(chrome web browser)  hover zoom+ Version 1.0.195

**Comment by extesy** [comment] 2022-08-10 03:14
Unable to reproduce, I've tried both old and new reddit designs 🤷🏻‍♂️

**Comment by zekecounter** [comment] 2022-08-10 03:25
> Unable to reproduce, I've tried both old and new reddit designs 🤷🏻‍♂️

Heres a video demonstration using  the link from example 1.  

- Hover cursor over post thumbnail, works fine 
- hover cursor over post title, doesnt do anything. 
- hover on the post title while in the actual thread/post, doesnt work either.


(NSFW)
https://streamable.com/8cwmqn

**Comment by extesy** [comment] 2022-08-10 04:39
Do you have redgifs plugin disabled by any chance? Please confirm in the [extension options](chrome-extension://oihocilbcniangoocnmimmnpmnackjgh/html/options.html) that it is enabled:

![image](https://user-images.githubusercontent.com/65872/183817049-c73f65d1-bf79-44d2-99f3-591f28f08f0e.png)

**Comment by zekecounter** [comment] 2022-08-10 16:33
> Do you have redgifs plugin disabled by any chance? Please confirm in the extension options that it is enabled (don't forget to press save button):
> 
> ![image](https://user-images.githubusercontent.com/65872/183817049-c73f65d1-bf79-44d2-99f3-591f28f08f0e.png)

oddly enough,  i figured.. why not try to disabled both of them.. guess what..  with those being ticked off, for some reason i was still able to use hoverzoom+ while hovering over thumbnails on reddit lmao. 

Figured i should uninstall and try again,welp...   turns out uninstalling and installing the extension fixed the issue 😂

**Comment by zekecounter** [comment] 2022-08-10 16:37
UPDATE:  seems like the issue is back whenever i enabled   "When you click on this extension"   and have reddit.com ticked. 

https://imgur.com/a/hNO6fq6

**Comment by extesy** [comment] 2022-08-10 23:54
Yeah, don't change its permissions to "on click" or "on specific website". It needs to work for all sites, like its default setting. It does not do anything nefarious, the source code is right here in the open. Closing the issue as invalid.

**Closed by extesy** 2022-08-10 23:54 UTC
Labels: can't reproduce

**Comment by yarub123** [comment] 2023-04-18 13:25
@extesy Only thing being "nefarious" is your dumbass being on redgifs 🤡

**Comment by yarub123** [comment] 2023-04-18 13:27
@zekecounter Why is your dumbass even on redgifs? Keep your degeneracy to yourself snowflake.
