### ISSUE TITLE
Mouse/cursor needs to have moved for image to zoom (reddit)

### ISSUE THREAD

**Issue by krombolopus** [extesy/hoverzoom#298] opened 2017-09-20 17:25 UTC
## Description of the problem
the mouse/cursor needs to move when hovered over an image to zoom, whereas you used to be able to just scroll past using the arrow keys and as the cursor passed over an image would zoom.

## Url of the page where the problem occurs (not the image url)
https://www.reddit.com/

## Steps to reproduce the problem (https://www.reddit.com/)
1.place cursor over an image submitted on the front page.
2.scroll front page using only arrow keys 
3.notice how other images dont zoom (some gifs do)

## OS version, extension version
windos 10 home 1703 OS Build 15063.608, chrome build Version 61.0.3163.91 (Official Build) (64-bit),
hoverzoom version -Version 1.0.123

**Comment by justhere4incrementals** [comment] 2017-09-28 05:47
I'm having the same issue. Until a few days ago, any image under the cursor would zoom. Now zoom doesn't enable until the cursor is moved. Bug can be reproduced in Google and Bing image searches.

**Comment by RhinoAus** [comment] 2017-10-01 05:47
I am also experiencing this issue. I was able simply use the arrow keys to scroll Reddit but now a mouse movement is required for the next image to load

**Comment by krombolopus** [comment] 2017-10-01 14:14
I'm thinking it may have something to do with RES, do other people have this?

**Comment by justhere4incrementals** [comment] 2017-10-02 06:04
I use RES; I disabled it, relaunched Chrome, and Hover Zoom still doesn't activate until the cursor moves. It's also stopped working in Google and Bing image searches, and any other website it would normally have this functionality, so I think it's unrelated to RES.

**Comment by FUCKHOVERZOOM** [comment] 2017-10-17 04:28
any update on the solution for this problem?

**Comment by ottos89** [comment] 2018-01-01 23:06
I'm having the same issue. I would love a solution

**Comment by topper2503** [comment] 2018-03-15 22:14
Seeing this issue too.

**Comment by tristo7** [comment] 2018-05-14 23:28
I ended up uninstalling this extension in favor of Imagus, due to this issue.

**Comment by csilvest** [comment] 2021-05-04 06:46
I have this issue in Chrome (at least)., when I use my scroll wheel to move the page up (or down), if an image lands under the cursor, HZ doesn't "see" the thumbnail and doesn't know to dig up the underlying image and zoom it.  Giving the mouse cursor a little move and then stopping motion with the cursor still on the thumbnail triggers HZ to do it's thing.

**Comment by LiliaDoe** [comment] 2024-11-06 23:07
What's causing this in the code is:
```js
$().each(function () {}))
``` 
This works just fine when the mouse doesn't move.
```js
$().('mouseover', function () {});
```

**Comment by extesy** [comment] 2024-11-07 00:41
Fixed by https://github.com/extesy/hoverzoom/commit/7ae5e25af15d385ceac53aa513ca426d44417366, will be available in the next release.

**Closed by extesy** 2024-11-07 00:41 UTC
