### ISSUE TITLE
Default download folder 

### ISSUE THREAD

**Issue by brucebcox** [extesy/hoverzoom#377] opened 2018-05-08 14:47 UTC
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem
Does not open last download folder used.  Always goes to DOWNLOADS.  This forces me to change folders with every download.  Works properly with other applications (download dialog opens last folder used), but not with hoverzoom.

## Url of the page where the problem occurs (not the image url)
Any and all pages or images.  Fails in Twitter, Tumblr, Facebook, etc.

## Steps to reproduce the problem (include image url here)
1. Hover
2. Press S for save
3. FIle dialog opens to DOWNLOADS rather than to the last folder selected.

## OS version, extension version (Chrome only, Firefox is not supported)
Google Chrome Version 66.0.3359.139 (Official Build) (64-bit)
Windows 10 Pro, version 1709, build 16299.371

**Comment by brucebcox** [comment] 2018-05-08 14:48
Sorry, forgot to include:
Version 1.0.129 - © 2014-2018 Oleg Anashkin

**Comment by extesy** [comment] 2018-05-08 15:12
@brucebcox This is not controlled by extension, this is a browser configuration. Use "settings" -> "downloads" to change it.

**Comment by ivan2340** [comment] 2018-05-08 15:15
This is a limitation of chromes download API, as far as I know there is no extension with the download permission that is able to download stuff to arbitrary directories, obviously this would be a huge security concern.

Maybe we can download the images via JS, store them in memory and then "save" them with an <a download>, however this might lead to ram issues with big video files

**Comment by ivan2340** [comment] 2018-05-08 15:16
@extesy this is actually a valid issue that we have no control of unfortunately.. But there might be a workaround

The behavior of the extension has changed due to my patch

**Comment by extesy** [comment] 2018-05-08 15:26
https://bugs.chromium.org/p/chromium/issues/detail?id=290562

**Comment by ivan2340** [comment] 2018-05-08 15:26
It's not a bug it's definetly intended behavior due to security concerns, there has however been a feature request for the API to allow for suggested Downloadpaths with a save dialog.

Downloading to memory using js might actually work as a workaround because the data isn't cross-domain then

**Comment by ivan2340** [comment] 2018-06-19 16:23
@extesy i am adding a pull-request this should be fixed now and the old behaviour restored :)

**Comment by ivan2340** [comment] 2018-06-21 16:11
@extesy fixed

**Closed** 2018-06-21 19:58 UTC
Labels: enhancement

**Comment by brucebcox** [comment] 2018-06-21 22:10
Yes, it's fixed.  Thanks!
