### ISSUE TITLE
HoverZoom is skipping to .mp4 url when viewing Rule34

### ISSUE THREAD

**Issue by evinnichenko** [extesy/hoverzoom#1493] opened 2024-12-08 04:29 UTC
**Describe the bug**
When trying to open a fullsize image from Rule 34's list pages (eg [this](https://rule34.xxx/index.php?page=post&s=list&tags=all)), according to the console it immediately skips to trying to open the .mp4 variant of the file, no matter the actual format.

**To Reproduce**
1. Go to a list page on Rule 34 (eg [this](https://rule34.xxx/index.php?page=post&s=list&tags=all)) (warning, NSFW)
2. Hover over any non-video object (without the blue border)
3. It tries to load the object forever
4. If you go to console, you will see that it tries to load the .mp4 file, and that it reports "Invalid URI".
5. Find a video object (eg go [here](https://rule34.xxx/index.php?page=post&s=list&tags=video)) and hover over it.
6. Video plays normally.

**Expected behavior**
Pictures (JPG, PNG, GIF) show up rather than infinite attempts at loading nonexistent video.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Confirmed on Firefox and Chrome
 - Version: HZ v.1.0.223

**Additional context**
Initially I was going to report it as "images not loading" but managed to trace it down to the issue described above and somewhere in the hoverzoom.js file; filters described in plugins/rule34.js work fine. The other websites work fine as far as I can see, and so does option to view full-size images from individual pic pages on rule34 (eg [this](https://rule34.xxx/index.php?page=post&s=view&id=11544686)); though I can't remember if it was a feature for _all_ pictures or only resized ones - because right now it only works for the latter.

**Comment by extesy** [comment] 2024-12-08 17:04
Duplicate of #1482, already fixed.

**Closed by extesy** 2024-12-08 17:04 UTC
