### ISSUE TITLE
i.imgur.gifv links not zooming

### ISSUE THREAD

**Issue by Alfie94** [extesy/hoverzoom#375] opened 2018-05-07 14:54 UTC
## Description of the problem
Hovering over an i.imgur.gifv link does not zoom the image

## Url of the page where the problem occurs (not the image url)
https://www.reddit.com/r/gifs/

## Steps to reproduce the problem (include image url here)
https://i.imgur.com/fPGqKEM.gifv

## OS version, extension version (Chrome only, Firefox is not supported)
Windows 10 64-bit
HoverZoom Version 1.0.129
Chrome Version 68.0.3418.2 (Official Build) dev (64-bit)

**Comment by extesy** [comment] 2018-05-07 17:47
Seems like a duplicate of #374

**Closed by extesy** 2018-05-07 17:47 UTC

**Comment by Alfie94** [comment] 2018-05-07 18:17
Just to confirm, it still works with i.imgur.gif but not i.imgur.gifv
