### ISSUE TITLE
Red loading icon (has imgError class) appears even in Whatsapp web and or text editors

### ISSUE THREAD

**Issue by dwengs** [extesy/hoverzoom#642] opened 2020-12-28 08:04 UTC
**Describe the bug**
In whatsapp web or even ckeditor plugin on websites, for about a few days (12-25-2020 and today) there is a "red loading icon". This icon shows for a few seconds and dissapears. I managed to check inspector and found it has id="hzImgLoader" and class="imgError"

**To Reproduce**
1. Go to Whatsapp web and or ckeditor plugin
2. Type something like "Malzeme"
4. See that red icon

**Screenshots**
![image](https://user-images.githubusercontent.com/17884352/103199620-4a461f00-48fc-11eb-87d5-4b4c36c9bd89.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 87
 - Extensions: Page Load time, Window Resizer, Page Ruler Redux, Awesome Screenshot, Adblock

It looks like it is trying to show some image even I'm not hovering.

# Edit
Looks like it only happens when I press "Z" key while cursor is hovering "iframe" of ckeditor and / or whatsapp typing inputs.

**Comment by extesy** [comment] 2020-12-28 18:04
This is the same complaint as in #639 caused by the change in color scheme. It used to have a less noticeable color. Should be fixed soon.

**Comment by dwengs** [comment] 2020-12-28 18:15
I think the problem is the fact that this loading icon is appearing even if I'm *NOT* hovering something. I'm okay with the colors etc.

**Comment by KaKi87** [comment] 2020-12-30 15:02
This red element also happens on Discord after clicking on a picture attachment.
Thanks

**Comment by GrosPoulet** [comment] 2020-12-30 17:47
Hi @KaKi87 
I did not manage to reproduce the issue on Discord, can you provide an url please ?

**Comment by KaKi87** [comment] 2020-12-30 18:51
In any guild, open any picture, from any message, and see the red element appear at top left :

![HoverZoomPlusDiscordBug](https://user-images.githubusercontent.com/21284089/103374599-466ef400-4ad8-11eb-94b9-dc45cc371a3a.gif)

**Comment by KaKi87** [comment] 2021-01-01 15:21
Actually, it also sometimes happen after sending messages and switching channels.

**Comment by brinkdinges** [comment] 2021-01-19 13:30
Today was the second time this loading image ended up in a WordPress post of mine. I'm not a fan of this new spinner.

**Comment by Industry** [comment] 2021-01-26 20:23
I experience this on WhatsApp too and some other websites. Had a hard time figuring out which of my plugins was causing it until seeing this thread. Another website where it's a problem is Pixlr.com

**Comment by Industry** [comment] 2021-01-26 21:03
Also happening in Outlook Webmail [screenshot](https://i.imgur.com/eIi4Tou.png).

**Comment by extesy** [comment] 2021-01-26 21:11
@GrosPoulet Maybe we should just remove the error spinner completely? The "in-progress" makes more sense but I don't see much use in the spinner after the image failed to load.

**Comment by KaKi87** [comment] 2021-01-26 21:20
Agreed. Please rollback everything. It was really great until then. 🙂

**Comment by GrosPoulet** [comment] 2021-01-26 21:25
Damned, everybody hates this poor little spinner :sob:
To be honest, me too, but it's very useful for debugging.
So i added an option to hide all spinners (in screenshot: "Display image loader" option):
- the green one : loading in progress
- the red one : loading failed
- the orange one (not pushed yet to github) : image skipped because user enabled options below "Display image loader".

![image](https://user-images.githubusercontent.com/23529041/105907258-13f7de80-6025-11eb-9bc9-9f62e04a5e62.png)
If it's ok for you, i'll try to push this stuff this week.

**Comment by KaKi87** [comment] 2021-01-26 21:28
Could you add an option to remove its color so it would become discreet again ? ^^

**Comment by GrosPoulet** [comment] 2021-01-26 21:30
It won't be displayed at all if you uncheck the option : "Display image loader"
Note: it will be unchecked by default.

**Comment by KaKi87** [comment] 2021-01-26 21:32
If I remember correctly, it used to only show up when the picture takes longer than usual to load. Right ?

**Comment by GrosPoulet** [comment] 2021-01-26 21:34
Red spinner is displayed when an error occurred while loading image (if you open the console you'll see more details)

**Comment by extesy** [comment] 2021-01-26 21:46
@GrosPoulet Can you please make that option off by default? Most users are lazy enough to not search for it in options but will still get annoyed by it.

**Comment by Industry** [comment] 2021-01-26 22:06
I second making it off by default given its main use is for debugging and less-than-helpful for most users

**Closed** 2021-05-02 13:38 UTC
Labels: bug, enhancement
