### ISSUE TITLE
The same image gets saved multiple times

### ISSUE THREAD

**Issue by desperte** [extesy/hoverzoom#1127] opened 2023-04-11 17:47 UTC
When hovering an image and pressing the "S" hotkey it downloads the image more than once, usually about 3 or 4 times, sometimes up to 10 times.
I tried changing the hotkey and still the same problem occurs. 

To Reproduce
Try to save an image with the "S" hotkey
Happens on Twitter and Yandex

On the latest version of Chrome and the latest version of HoverZoom

**Comment by SirGer** [comment] 2023-04-11 18:48
Hover Zoom+ Version 1.0.204  / Chrome (version noted below)

Windows 10 Home 21H2 10.0.19044.2728 / Windows Feature Experience Pack 120.2212.4190.0
HP ENVY x360 m6 Convertible / Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz   2.90 GHz

All of a sudden the Save action is downloading **3 copies** of an image instead of just one; no known updates prior to the onset of this problem except enable/disable another extension as noted below *

Tried updating Chrome to Version 112.0.5615.50 (Official Build) (64-bit) - no joy.

**Removed and reinstalled HZ+ from Chrome Webstore, default settings.** 
The first time I use HZ+ Save (on a thumbnail in a DuckDuckGo image search result page) a pop-up (that does not go away) says HZ+ is requesting additional permissions - allow it to manage downloads? 
**When I click 'Allow' a _single_ download happens. _But from then on any Save is triple_.**

Help? Thx!
* The problem could be associated with having enabled and then disabled an extension called "Always Clear Downloads 2" which was already installed.in Chrome but disabled. I have completely Removed this extension now but the above problem persists.

**Comment by extesy** [comment] 2023-04-11 19:31
@GrosPoulet Another hotfix needed?

**Comment by GrosPoulet** [comment] 2023-04-11 20:17
Yep, i fear so. I'll fix it tomorrow.

**Comment by TS6ix2GaH3q679h5** [comment] 2023-04-11 23:13
Same behavior happening for me.
Version 1.0.204 (last update: Mon, Apr 10, 2023)

**Comment by mcdoncod** [comment] 2023-04-12 01:22
Same for me

**Comment by miklosUX** [comment] 2023-04-13 11:48
Same sheite for me 🤬

**Comment by Is0kaze** [comment] 2023-04-14 05:29
The same problem persists with me... reinstalling the extension or resetting the permissions doesn't solve anything :(

**Comment by extesy** [comment] 2023-04-15 04:57
@All - the fix is being actively worked on, please wait for updates.

**Comment by extesy** [comment] 2023-04-17 05:18
This should be fixed now, please try version 1.0.205. Thank you @GrosPoulet for the fix.

**Closed by extesy** 2023-04-17 05:18 UTC
Labels: bug

**Comment by SirGer** [comment] 2023-04-17 06:18
Please update version on Chrome Webstore to 1.0.205?
Thanks to all for efforts involved in fixing this bug; wondering why it suddenly appeared within a working version 204, but no matter...
GC
    On Monday, April 17, 2023 at 01:18:55 AM EDT, Oleg Anashkin ***@***.***> wrote:  
 
 


This should be fixed now, please try version 1.0.205. Thank you @GrosPoulet for the fix.

**Comment by EnverAvci** [comment] 2023-04-17 16:17
Google chrome also has Version 1.0.204 at the moment I will wait for it to be updated to version 205.

**Comment by EnverAvci** [comment] 2023-04-19 13:54
I updated to version 1.0.205 and now it doesn't download at all.

**Comment by EnverAvci** [comment] 2023-04-19 13:55
> Bu şimdi düzeltilmelidir, lütfen 1.0.205 sürümünü deneyin. Teşekkür ederim@GrosPouletdüzeltme için

I updated to version 1.0.205 and now it doesn't download at all.

**Comment by SirGer** [comment] 2023-04-19 14:27
I too UNTIL I found (or recalled? new or old element?) that you have to enable the first option (Allow Downloads) on the Advanced tab after entering the 'Extension Options' pages from the main extension.
    On Wednesday, April 19, 2023 at 09:55:15 AM EDT, ENVER AVCI ***@***.***> wrote:  
 
 



Bu şimdi düzeltilmelidir, lütfen 1.0.205 sürümünü deneyin. Teşekkür ***@***.***üzeltme için


I updated to version 1.0.205 and now it doesn't download at all.

**Comment by SirGer** [comment] 2023-04-19 14:27
I too UNTIL I found (or recalled? new or old element?) that you have to enable the first option (Allow Downloads) on the Advanced tab after entering the 'Extension Options' pages from the main extension.   On Wednesday, April 19, 2023 at 09:54:45 AM EDT, ENVER AVCI ***@***.***> wrote:  
 
 


I updated to version 1.0.205 and now it doesn't download at all.

**Comment by EnverAvci** [comment] 2023-04-19 14:41
> Ben de ana uzantıdan 'Uzantı Seçenekleri' sayfalarına girdikten sonra Gelişmiş sekmesindeki ilk seçeneği (İndirmelere İzin Ver) etkinleştirmeniz gerektiğini buldum (veya hatırladım mı? yeni veya eski öğe?). 19 Nisan 2023 Çarşamba günü saat 09:54:45 EDT'de ENVER AVCI ***@***.***> şunu yazdı: 1.0.205 sürümüne güncelledim ve şimdi hiç indirmiyor. — Bu e-postayı doğrudan yanıtlayın, GitHub'da görüntüleyin veya abonelikten çıkın. Bunu yorum yaptığınız için alıyorsunuz.Mesaj Kimliği: ***@***.***>

I checked the information you wrote, my problem continues.

**Comment by SirGer** [comment] 2023-04-19 17:07
When you Check the "Allow Downloading images using an Action Key" box on the 'Advanced' page you need to click 'Allow' on the "Hover Zoom+ has requested additional permissions / It could manage your downloads" pop-up that appears, and then click SAVE at the bottom of the page (also reload any pages where you want to download...)
if you had previously customized by using the "Save images & videos to folder: Downloads/" field then after installing the new version you may need to reestablish this, e.g. withHZ+/  (for a /Downloads/HZ+/ folder)
That's all I can think of for you...

G


    On Wednesday, April 19, 2023 at 10:41:17 AM EDT, ENVER AVCI ***@***.***> wrote:  
 
 



Ben de ana uzantıdan 'Uzantı Seçenekleri' sayfalarına girdikten sonra Gelişmiş sekmesindeki ilk seçeneği (İndirmelere İzin Ver) etkinleştirmeniz gerektiğini buldum (veya hatırladım mı? yeni veya eski öğe?). 19 Nisan 2023 Çarşamba günü saat 09:54:45 EDT'de ENVER AVCI @.> şunu yazdı: 1.0.205 sürümüne güncelledim ve şimdi hiç indirmiyor. — Bu e-postayı doğrudan yanıtlayın, GitHub'da görüntüleyin veya abonelikten çıkın. Bunu yorum yaptığınız için alıyorsunuz.Mesaj Kimliği: @.>


I checked the information you wrote, my problem continues.

**Comment by SirGer** [comment] 2023-04-19 21:24
You're welcome. I had to rediscover this when I installed the latest/fixed 1.0.205 version and I know how frustrating that was.
Actually it may be a new feature - as I recall in 204 the pop-up was appearing after re-install only when you attempted your first download, and it stayed on screen after clicking 'Allow'... I reported this, so possibly I was the cause of a new option being added for downloading so that the pop-up could be controlled from the page and not at run-time?
I had no specific recollection of the option when I "rediscovered" it after installing 205, and it did not give me an 'Oh yeah..." feeling. If new then a pity it was not announced along with the fix in 205.
But all's well that ends well...
Gerry
    On Wednesday, April 19, 2023 at 01:26:33 PM EDT, ENVER AVCI ***@***.***> wrote:  
 
 



When you Check the "Allow Downloading images using an Action Key" box on the 'Advanced' page you need to click 'Allow' on the "Hover Zoom+ has requested additional permissions / It could manage your downloads" pop-up that appears, and then click SAVE at the bottom of the page (also reload any pages where you want to download...) if you had previously customized by using the "Save images & videos to folder: Downloads/" field then after installing the new version you may need to reestablish this, e.g. withHZ+/  (for a /Downloads/HZ+/ folder) That's all I can think of for you...



Yes I have solved the problem now thank you. I've checked the option here. I've accepted the permissions and now it downloads without problems.
Thank you for your help.
