### ISSUE TITLE
Pinterest

### ISSUE THREAD

**Issue by breatme** [extesy/hoverzoom#312] opened 2017-10-16 18:08 UTC
Hello,

**Description of the problem**
The plugin don't working for https://www.pinterest.fr since some days.
I need to click on a picture then the home page for the plugin to work, before this step was not necessary.

**Url of the page where the problem occurs (not the image url)**
https://www.pinterest.fr

**Steps to reproduce the problem (include image url here)**
Just go on pinterest french version website

**OS version, extension version**
Windows 10 (1703)
Hover Zoom+ 1.0.123

Do you have a solution ?

**Comment by extesy** [comment] 2017-10-16 23:04
Duplicate of #272

**Closed by extesy** 2017-10-16 23:04 UTC
