### ISSUE TITLE
v.redd.it videos no audio on hover

### ISSUE THREAD

**Issue by k1ngisamu** [extesy/hoverzoom#758] opened 2021-07-23 02:57 UTC
Reddit videos no audio on hover (v.redd.it)

reddit.com (v.redd.it)

1. go to reddit
2. hover over a v.redd.it link
3. no audio plays on hover

windows 10, hoverzoom 1.0.176 , chrome 92.0.4515.107 (64 bits)

**Comment by gody93** [comment] 2021-07-23 12:52
They fixed it and it will be added on 1.0.177

https://github.com/extesy/hoverzoom/issues/756

**Comment by Ikbenik5** [comment] 2021-07-23 13:58
@gody93 Hi, when will the 1.0.177 update be available?

**Comment by extesy** [comment] 2021-07-23 16:13
Closing as a duplicate of #756

**Closed by extesy** 2021-07-23 16:13 UTC

**Comment by extesy** [comment] 2021-07-23 16:21
The new version will be available as soon as Google approves it and distributes to your browsers.
