### ISSUE TITLE
Save & Copy feature is not working with hot keys as explained

### ISSUE THREAD

**Issue by star777star** [extesy/hoverzoom#1268] opened 2023-11-19 08:23 UTC
**Describe the bug**
Save & copy feature is not working as explained. only few options is Flip,Close,OPen in new tab, open in new window works.

**To Reproduce**
Launch google image website with search for "Sunflower" .
Resultant page shows many sunflower images.
Hover any image and wait until the image popup opens, then click S (to save) is not working and Click C (to copy) is also not working.

**Expected behavior**
Both Save & Copy feature to be work as explained 

**Screenshots**
NA

**Desktop (please complete the following information):**
 - Windows 10. 64-bit, Build 19045
 - Firefox 119.01, 64-bit 

**Additional context**

**Comment by extesy** [comment] 2024-05-30 22:19
Duplicate of #978

**Closed by extesy** 2024-05-30 22:19 UTC
Labels: bug, firefox
